"""Permission repository port."""

from typing import Protocol
from uuid import UUID

from app.modules.permissions.domain.models import Permission


class PermissionRepository(Protocol):
    def add(self, permission: Permission) -> Permission: ...
    def list(self) -> list[Permission]: ...
    def get(self, permission_id: UUID) -> Permission | None: ...
    def get_by_code(self, code: str) -> Permission | None: ...
    def save(self, permission: Permission) -> Permission: ...

