"""User repository ports."""

from typing import Protocol
from uuid import UUID

from app.modules.roles.domain.models import Role
from app.modules.users.domain.models import User, UserRole


class UserRepository(Protocol):
    def add(self, user: User) -> User: ...
    def list(self) -> list[User]: ...
    def get(self, user_id: UUID) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...
    def get_by_username(self, username: str) -> User | None: ...
    def save(self, user: User) -> User: ...


class UserRoleRepository(Protocol):
    def get_assignment(self, user_id: UUID, role_id: UUID) -> UserRole | None: ...
    def add(self, assignment: UserRole) -> UserRole: ...
    def list_roles(self, user_id: UUID) -> list[Role]: ...
    def remove(self, assignment: UserRole) -> None: ...

