"""Role repository ports."""

from typing import Protocol
from uuid import UUID

from app.modules.permissions.domain.models import Permission
from app.modules.roles.domain.models import Role, RolePermission


class RoleRepository(Protocol):
    def add(self, role: Role) -> Role: ...
    def list(self) -> list[Role]: ...
    def get(self, role_id: UUID) -> Role | None: ...
    def get_by_name(self, municipality_id: UUID, name: str) -> Role | None: ...
    def save(self, role: Role) -> Role: ...


class RolePermissionRepository(Protocol):
    def get_assignment(
        self, role_id: UUID, permission_id: UUID
    ) -> RolePermission | None: ...
    def add(self, assignment: RolePermission) -> RolePermission: ...
    def list_permissions(self, role_id: UUID) -> list[Permission]: ...
    def remove(self, assignment: RolePermission) -> None: ...

